# Generated by Django 4.0 on 2022-01-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0005_alter_tshirt_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idealfor',
            options={'verbose_name': 'Idealfor', 'verbose_name_plural': 'Idea For'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'verbose_name': 'occasions', 'verbose_name_plural': 'Occasion'},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('sizeVariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sizevariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
