# Generated by Django 4.0 on 2022-01-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_idealfor_options_alter_occasion_options_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
