# Generated by Django 4.0 on 2022-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cart_options_rename_quantity_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sizeVariant',
        ),
        migrations.AddField(
            model_name='cart',
            name='sizeVariant',
            field=models.ManyToManyField(to='store.Sizevariant'),
        ),
    ]
