# Generated by Django 4.0 on 2022-01-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0010_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_statu', models.CharField(choices=[('PANDING', 'pending'), ('PLACED', 'placed'), ('CANCELED', 'canceled'), ('COMPLETE', 'complet')], max_length=15)),
                ('payment_method', models.CharField(choices=[('COD', 'cod'), ('ONLINE', 'online')], max_length=15)),
                ('shiping_address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'BRAND'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'CART'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'COLOR'},
        ),
        migrations.AlterModelOptions(
            name='idealfor',
            options={'verbose_name': 'Idealfor', 'verbose_name_plural': 'IDEAL FOR'},
        ),
        migrations.AlterModelOptions(
            name='necktype',
            options={'verbose_name_plural': 'NECK TYPE'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'verbose_name': 'occasions', 'verbose_name_plural': 'OCCASION'},
        ),
        migrations.AlterModelOptions(
            name='sleeve',
            options={'verbose_name_plural': 'SLEEVE'},
        ),
        migrations.AlterModelOptions(
            name='tshirt',
            options={'verbose_name_plural': 'TSHIRT'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='FAILED', max_length=15)),
                ('payment_id', models.CharField(max_length=60)),
                ('payment_request_id', models.CharField(max_length=60, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sizevariant')),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tshirt')),
            ],
        ),
    ]
