# Generated by Django 4.0 on 2022-01-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_alter_brand_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'ORDER'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'ORDER ITEMS'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'PAYMENT'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_statu',
            new_name='order_status',
        ),
    ]
