# Generated by Django 4.0 on 2022-01-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshirt',
            old_name='deal_for',
            new_name='Ideal_for',
        ),
    ]
