# Generated by Django 4.0 on 2022-03-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'SLIDER'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(upload_to='upload/image'),
        ),
    ]
