# Generated by Django 4.0 on 2022-03-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_slider_options_alter_slider_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
